Welcome you logged in person!
This is where you can do things with the app!
<a href="/">public home</a>


<!--<h3 id="links" class="subhead">Connect with Me</h3>-->
<div class="row">
    <div class="col-md-12 col-sm-12 benefit">
        <a href="/car">
            <div class="benefit-ball">                
                <span class="fa fa-car" style="font-size:4em">
            </div>
        </a>
    </div> <!-- /.benefit -->

    <div class="col-md-12 col-sm-12 benefit">
        <a href="">
            <div class="benefit-ball">
                <span class="glyphicon glyphicon-inbox"></span>
            </div>
        </a>
        <h3>Do Stuff</h3>
        <p>The good kind of stuff</p>
    </div> <!-- /.benefit -->
</div> <!-- /.row -->	